BOJ/jeongbeen/1_week/임스와함께하는미니게임.java
Java의 HashSet 을 활용하여 이름을 중복되지 않게 넣은 후에 선택된 게임에 따라 각각 1, 2, 3 으로 나눠준 값을 출력하였습니다.
원래 c++이나 python 으로 하다가 이번 기회에 Java 로 해보려고 합니다. 미숙한 부분이 있으면 알려주시면 감사하겠습니다!
=> [Baekjoon-25757] jeongbeen

BOJ/yein/1_week/블로그.py
**1. 입력값 처리 및 사용한 변수 설명**
- 블로그 총 운영 일수 days, 조회할 기간을 x 변수에 받았습니다.
- days 동안의 방문자 수를 arr 배열에 받아 저장했습니다.
- visitors 배열에는 x일간의 조회수를 저장할 것입니다.
**2. 사용된 알고리즘은 "슬라이딩 윈도우 알고리즘"입니다.**
- 매번 x번씩 모두 더하게 되면 "시간초과"로 문제를 풀 수가 없었습니다.
- 맨 처음 구간에 대해서는 x개만큼의 합을 구합니다.
- 다음 구간을 구하기 위해, 맨 앞 날짜의 조회수를 버리고 새로운 날짜의 조회수를 더해주는 방식으로, x번씩 더하지 않고도 원하는 결과를 얻을 수 있었습니다.
**3. 리턴값: 최대값이 등장한 횟수 세기**
- 최대값을 구하기 위해 max() 함수를 사용하였습니다.
- visitors 배열을 순회하며 최대값과 동일한 값이 등장하면 count를 하나 증가시키는 방법을 사용하였습니다.
=> [Baekjoon-21921] yein

BOJ/yein/1_week/임스와 함께하는 미니게임.py
**1. 입력값 및 사용한 변수 설명**
- 게임을 신청한 인원 수 n, 수행할 게임 종류를 game 변수에 받았습니다.
- arr 배열에, n번만큼 게임을 신청한 사람들의 id를 받습니다.
- need는 game 종류에 따른 필요 인원수에서 임스를 제외하여 1을 뺀 수를 저장하였습니다.
**2. 문제 해결을 위해 사용한 주요 기능은 set( ) 입니다.**
- arr에 id를 모두 받은 후, arr를 set으로 변환하였습니다.
- set 변환 후 남은 요소들의 길이를 게임에 필요한 인원수로 나눠 그 몫만큼 게임이 수행되는 것으로 계산하였습니다.
=> [Baekjoon-25757] yein

BOJ/jihoon/1week/블로그.cpp
21921 문제는 **슬라이딩 윈도우 알고리즘** 문제입니다.
이런 문제의 경우 특정 알고리즘을 안 쓴다면 반복문을 여러번 쓰게 하는데, 최악의 경우를 확인해서 시간을 측정해봐야 합니다. 
해당 문제의 시간 제한은 1초이므로, O(N)의 경우 N은 1억의 값, O(N^2)의 경우 N은 약 1만번이 최대가 됩니다. ( 총 연산 횟수가 1억이 1초라고 생각하면 편할 것 같습니다.)
이 문제에서 N과 X의 최댓값은 250,000, 방문자 수의 최댓값은 8,000입니다. 만약 X가 1만이고, N이 25만 이라면 반복문의 횟수는 `O(N * X)` 이며 `O(240,000 * 10,000)` 이므로 1억번을 훌쩍 뛰어 넘습니다.
하지만 만약 **슬라이딩 윈도우**를 써서 0번째 인덱스부터 X번째까지 인덱스의 합을 구하고, 첫 값을 빼고 남은 N-X의 값을 더하는 것만 반복하면 되기 때문에, 시간 복잡도는 `O(X) + O(N-X) = O(N)`이 되게 됩니다. N의 최댓값은 25만이므로 1초 안에 통과할 수 있게 됩니다.
=> [Baekjoon-21921] jihoon

BOJ/jeongbeen/1_week/블로그.java
먼저 X의 개수만큼 배열의 앞부터 방문자 수를 계산합니다. (1\~X일까지의 방문자 수)
이제 1번째 날의 방문자 수를 빼고, X+1번째 날의 방문자 수를 더하면  2\~X+1까지의 방문자 수가 나옵니다.
N까지 이를 반복하여 최댓값을 탐색합니다.
이중 반복문을 사용하지 않고 차이가 나는 양쪽 끝 원소의 값만 바꾸는 이 방법을 슬라이딩 윈도우라고 합니다.
max 값이 갱신될 때마다 maxCount 값을 1로 초기화 합니다. 이후에 max 값과 같은 값이 나온다면 maxCount 값을 1 증가시킵니다.
Java 로 코테가 처음이라 적극 피드백 해주시면 감사하겠습니다!!
=> [Baekjoon-21921] jeongbeen

BOJ/yein/2_week/차집합.py
'차집합'이라는 수학적인 개념은 구현하는 데 어렵지 않았지만
시간초과 때문에 정말 많이 애먹은 문제였습니다...
**입력 처리**
na, nb에 a, b의 길이를 받았습니다. 실제로 활용되진 않았습니다.
a, b 각각에 요소들을 입력 받았습니다.
**연산**
파이썬에서는 set 간 차집합 연산을 간단하게 구현할 수 있습니다.
주석처리해둔 리스트 반복문의 경우 O(na*nb)의 복잡도를 가지지만,
set 차집합의 연산은 O(min(na, nb))의 복잡도를 가진다고 합니다.
=> [Baekjoon-1822] yein

BOJ/jeongbeen/2_week/비슷한_단어.java
1. 알파벳을 count 할 수 있는 26 크기의 배열 생성.
2. 첫 번째 단어의 구성을 배열에 저장
3. 나머지를 비교하며 새로 구성된 배열과 비교
두 단어의 구성 요소 중 가능한 것은
(1). 똑같은 구성
(2). 알파벳 하나가 추가로 있거나 없거나
(3). 알파벳 하나가 바뀐 구성
이 비교를 위해 difference 라는 변수를 정의하였고, difference는 각 알파벳의 차이의 합 입니다.
difference 는 한번 -1로 갔다면 그대로 있거나, 0으로 오고 난 뒤에는 알파벳의 차이가 있으면 안됩니다.
마찬가지로 한번 1로 가면 그대로 있거나 0으로 온 뒤에는 다시 차이가 발생하면 안됩니다.
이 규칙을 지켜 통과하는 단어는 answer를 증가시켰습니다.
시간을 재고 막 풀어서 코드가 좀 보기 그런데 다른 분들 코드 열심히 보고 배우겠습니다.
=> [Baekjoon-2607] jeongbeen

BOJ/seulah/2_week/차집합.py
**언어:** 파이썬
- `Set` 자료형을 활용하여 두 집합을 입력받아 차집합 연산 `A-B` 수행했습니다.
**참고한 내용**
> 처음에 차집합 결과를 A-B로 하여 출력하였는데 결과 값은 그대로 나왔으나 실패하여 이유를 찾고자 `Set` 자료구조 내용을 참고하였습니다.
-   Set은 기본적으로 정렬되지 않은 자료구조이기 때문에 차집합 결과를 그대로 출력하면 출력 형식이 달라 질 수 있기 때문에 `sorted`를 사용해 정렬해주어야 합니다.
> `set`을 숫자형 값으로 출력하는 방법이 생각나지 않아 참고하였습니다...........
- `print(" ".join(map(str, result)))`  을 통해 숫자를 문자열로 변환한 후 공백으로 구분하여 출력하였습니다
=> [Baekjoon-1822] seulah

BOJ/minji/1_week/차집합.py, BOJ/minji/2_week/비슷한단어.py
-Counter
Counter은 collections 모듈에서 제공하는 자료형으로 요소의 개수를 셀 수 있다. word1과 word2의 각 문자가 몇 번 등장하는지 센다. 
```
Counter({'D': 1, 'O': 1, 'C': 1}) # DOC의 Counter
Counter({'L': 2, 'D': 1, 'O': 1} #DOLL의 Counter
```
두 Counter의 차이를 비교하기 위해 - 연산자를 사용하였다. 
```
count1 = Counter("abracadabra")
count2 = Counter("ab")
result = count1 - count2
#출력결과
#Counter({'a': 3, 'r': 2, 'b': 1, 'c': 1, 'd': 1})
```
차이나는 문자의 개수를 세기 위해 sum((count1 - count2).values()) 와 같은 방식을 사용하여 각각 diff1과 diff2에 저장한다.
- isSimilar 함수
두 단어의 길이가 2이상 차이나는 경우는 False를 반환, 두 Counter가 완전히 동일한 경우는 True를 반환한다.
두 단어의 길이가 동일한 경우에는 diff1과 diff2가 모두 1인 경우 (한 단어만 교체) True를 반환한다.
word1이 word2보다 긴 경우, diff1의 값이 1이고 diff2의 값이 0인 경우(한 단어 추가) True를 반환한다
word2이 word1보다 긴 경우, diff1의 값이 0이고 diff2의 값이 1인 경우(한 단어 추가) True를 반환한다
나머지 경우는 False를 반환한다.
=> [Baekjoon-2607] minji

BOJ/seulah/2_week/비슷한 단어.py
**언어 : 파이썬**
_ps. 굉장히 ... 오래 걸렸습니다.... 자료를 참고하였지만 
다른 자료들을 참고하면서 제가 이해하기 쉬운 풀이로 만들고자 노력했습니다_
**비슷한 단어 판단 조건**
- 동일한 길이와 동일한 알파벳 구성 => 길이가 같고 빈도차가 0
- 문자 변경 (교체) => 길이가 같고 빈도차가 2
- 문자 추가/삭제 => 길이 차이가 1이고 빈도차가 1
**1) 입력 처리**
`target`:  기준 단어
`words`: 비교할 단어 목록
**2) 빈도 계산**
각 알파벳의 빈도수를 계산하기 위해 `Counter`를 사용했습니다
- `target_cnt`: 기준 단어의 문자 빈도를 계산
> target_cnt = Counter("DOG")  # {'D': 1, 'O': 1, 'G': 1}
- `word_cnt`: 현재 비교 중인 단어의 문자 빈도를 계산
> current_count = Counter("GOOD")  # {'G': 1, 'O': 2, 'D': 1}
**3) 문자 차이 계산**
`set 함수`와 숫자의 절댓값을 반환하는 내장 함수 `abs` 활용
- `all_chars`:  기준 단어와 현재 단어의 모든 문자의 집합.
> all_chars = set(target_cnt) | set(word_cnt)  # {'D', 'O', 'G'}
- `diff += abs(target_cnt[char] - word_cnt[char])` : 빈도 차이 누적
> 'D': abs(1 - 1) = 0
> 'O': abs(1 - 2) = 1
> 'G': abs(1 - 1) = 0
>  diff = …
=> [Baekjoon-2607] seulah

BOJ/minji/2_week/덩치.py
- 부르트포스 알고리즘
brute: 무식한, force: 힘. 가능한 모든 경우의 수를 탐색하는 알고리즘
- 입력, 값 초기화
입력 받은 키와 몸무게를 [h, w] 형태로 저장하여 이를 hwList에 저장한다. 결과적으로 2차원 배열의 형태로 저장된다.
countList는 각 사람의 덩치 등수를 저장하는 역할을 한다.
- 부르트포스 알고리즘을 활용한 비교
이중 for문을 사용하였다. i와 j는 기준이 되는 사람 (i), 비교할 사람(j)의 인덱스가 된다.
현재 자신보다 덩치가 큰 사람의 수를 저장하는 tmpCount 변수를 1로 초기화 한다.(자신보다 더 큰 덩치의 사람이 k명이라면 그 사람의 덩치 등수는 k+1이기 때문)
hwList[i][0] (i의 몸무게)와 hwList[j][0] (j의 몸무게)를 비교, hwList[i][1] (i의 키)와 hwList[j][1] (j의 키) 를 각각 비교하여 키와 몸무게의 값이 모두 더 큰 경우, tmpCount의 값을 1더한다. 바깥쪽 for문이 한 번 돌 때마다 tmpCount를 countList에 추가한다.
- 출력
countList의 값을 차례로 출력한다.
=> [Baekjoon-7568] 타임어택_문제 풀이

BOJ/yein/2_week/덩치.py
시간 안에 풀지 못했습니다 ㅠㅠ.....
처음에 sort를 해서 문제를 풀다가, 최종 출력에서 원본의 순서를 잃고 한참 헤맸습니다...
**입력 처리 및 배열 초기화**
먼저, 각 사람들의 정보는 arr 배열에 배열로 받습니다. arr[-][0]에는 몸무게, arr[-][1]에는 키가 들어갑니다.
rank는 모두 1로 초기화해줍니다. arr의 인덱스와 rank의 인덱스는 동일한 사람의 정보를 나타냅니다.
**계산과정**
**덩치 등수**란 곧 나보다 **덩치가 큰 사람들의 수+1**과 같습니다.
이 논리를 이용해 이중 반복문을 사용하여 구현하였습니다.
=> [Baekjoon-7568] 타임어택_덩치

BOJ/jeongbeen/3_week/설탕_배달.java
효율적으로 배달하기 위해, 3킬로그램 봉지는 0개에서 4개만 가능
(3과 5의 최소공배수는 15이기 때문..)
따라서 3킬로그램 봉지가 0, 1, 2, 3, 4인 경우 5로 나눠지는지 확인하고 사용한 봉지의 개수를 더함
\~끝\~
=> [Baekjoon-2839] jeongbeen

BOJ/yein/3_week/설탕 배달.py
문제를 시작하기에 앞서...
다이나믹 프로그래밍을 연습해보고 싶어서, 다이나믹 프로그래밍 문제 중 낮은 티어의 문제를 골랐습니다.
근데 다이나믹 프로그래밍을 쓰지 않아도 문제가 풀리더라구요...
**입력값 및 변수 초기화**
`n`에 총 설탕 무게를 입력 받았습니다.
`answer`는 -1(실패)를 기본값으로, 정답을 받을 때는 
nkg 중 5키로로 들 수 있는 최대 개수를 위해 n을 5로 나눈 몫을 `max5`에 저장했습니다
**문제풀이 방식**
사용된 알고리즘은 `그리디 알고리즘` 과 `브루트포스 알고리즘` 입니다.
최대한 많은 개수의 5kg 봉지를 들게 하지만,
동시에 딱 떨어지는지를 찾기 위해 5kg 봉지를 하나씩 빼 가며, 5kg 봉지를 드는 모든 경우를 전수조사하였습니다.
마지막으로, 나눗셈의 결과 때문에 실수 타입이 되었기 때문에, int형으로 캐스팅하여 출력하였습니다.
=> [Baekjoon-2839] yein

BOJ/yein/3_week/주식.py
**입력값 및 변수 설명**
`test_n`에 테스트케이스 수를 입력 받습니다.
테스트케이스 수만큼 순회하며, 일자 수 `days_n`과 주식 가격 `arr` 를 입력 받습니다.
`profit`에는 계산된 이득을 모두 더해 최종 출력값을 구합니다. `max_price`는 현재의 최대값을 의미합니다.
**문제풀이 방식**
풀이에 사용된 알고리즘/기법은 **`역순 탐색`** 과 **`그리디 알고리즘`** 입니다.
`역순 탐색`: 현 위치보다 오른쪽(미래)에 있는 값들의 최대값이 필요하였는데, 슬라이싱과 max를 사용하면 복잡도가 매우 커지게 되는 문제를 겪었습니다.
이 방식을 거꾸로 해석하여, 역순으로 탐색을 진행하면 미래의 최대값을 덜 복잡한 방법으로 구할 수 있게 됩니다.
`그리디 알고리즘`: 오늘이 최대값이면 다 팔고, 오늘이 최대값이 아니면 사서 이득을 얻는 방법입니다.
=> [Baekjoon-11501] yein

BOJ/jihoon/3week/주식.cpp
11501 문제는 그리디 알고리즘으로 풀었습니다.
먼저 날의 최대 수는 1,000,000이고 각 날의 최대 주가는 10,000이므로 주식의 최대이익이 약 20억은 훌쩍 넘으므로 최종 최대 이익 반환 값은 long long 타입을 지정했습니다.
방법은 총 2가지로 생각했습니다.
1. 앞부터 계산 2. 뒤부터 계산 => 저는 뒤부터 계산하는 것으로 선택했습니다.
그 이유는 앞부터 계산할 때, 최댓값이 나올 때까지 각 이윤을 계산해서는 안되기 때문에, 먼저 순차적으로 어느 위치에 구간별 최댓값이 존재하는지 확인해야 합니다.
해당 과정은 N번부터 0번까지 순회하는 for문으로 구성됩니다. 그리고 0번부터 N번까지 for문을 다시 돌며, 구간별 최댓값이 등장할 때까지 이윤을 더하는 과정을 반복해야 합니다.
이 방법은 for문이 한번이므로 O(N)이지만 테스트케이스인 T의 값이 나오지 않았다는 것이 문제입니다. T에 따라 O(N)이 몇 번 반복 될지 모르기 때문에, 같은 O(N)이라도 최적화해야 합니다.
따라서 1번 과정에서 구간별 최댓값을 구하는 과정에 max - 자신 값을 바로 계산하여 최대 이윤을 for문 한번으로 구할 수 있는 2번 방법을 채택하여 문제를 해결했습니다.
꽤나 어렵,,,
=> [Baekjoon-11501] jihoon

BOJ/minji/3_week/설탕배달.py
- 값 초기화
먼저 n을 5로 나누어 몫을 구하고, 이를 cnt에 저장한다.
x는 n을 5로 나눈 몫에 5를 곱한 값으로 5의 배수 중 가장 큰 값을 찾는다.
- 답 구하기
만약 x가 n과 같다면 n은 이미 5의 배수이므로 답을 바로 구할 수 있다. 
x가 n과 다르면, x를 5씩 줄여가며 (n - x) % 3 == 0이 될 때까지 확인한다.
5의 배수 부분을 줄일 때마다, cnt도 1씩 감소시킨다.
만약 x가 0보다 작아지면 n을 5와 3의 합으로 표현할 수 없으므로 -1을 출력한다.
나머지가 3의 배수가 되면, 남은 값만큼 3의 개수를 더하여 최종 결과를 구한다.
최종적으로 5와 3의 개수를 합산하여 답을 출력한다.
=> [Baekjoon-2839] minji

BOJ/seulah/3_week/설탕 배달.py
처음에 문제를 보고 거스름돈 구하는 문제처럼 접근하면 되겠다고 생각한 뒤 문제를 풀었습니다 :)
--------
`if N % 5 == 0`:  5kg 봉지로 나눌 수 있는지 확인하고 
나눠떨어질 경우, bags += N // 5로 5kg 봉지의 개수를 더합니다.
5kg 봉지로 나누어 떨어지지 않는 경우에는  
`N -= 3`: 3kg 봉지 하나를 추가하고 설탕 무게를 3kg 줄입니다.
bags += 1: 3kg 봉지를 사용했으므로 봉지 개수를 1 증가시킵니다.
=> [Baekjoon-2839] seulah

BOJ/minji/3_week/설탕배달.py, BOJ/minji/3_week/주식.py
- 주식 가격 탐색
주식 가격 배열 x에서 최대 이익을 얻기 위해서는 뒤에서부터 순차적으로 가격을 확인한다.
max_price는 현재까지 본 주식 가격 중 가장 높은 가격을 저장한다.
profit은 주식 가격을 사고 팔아서 얻은 총 이익을 누적해서 저장한다.
만약 현재 가격이 max_price보다 크면 그 가격을 max_price로 갱신한다.
반대로 현재 가격이 max_price보다 작으면 현재 가격으로 팔고 이익을 얻을 수 있다.
이때 얻은 이익은 max_price - x[i]로 계산되며 이를 profit에 더한다.
모든 주식 가격을 탐색한 후 최종적으로 계산된 profit을 반환한다.
=> [Baekjoon-11501] minji

BOJ/jaehong/3_week/설탕배달.java
이번 문제는 생각보다 간단하네요!
1. 5로 나누어 떨어질 때까지 n에서 3kg씩 뺍니다
2. n이 0이 되거나 음수가 되기 전까지 위에 과정을 반복합니다
3. n이 정확히 0이 되면 최소 봉지 개수를 출력합니다
4. 예외는 -1로 처리합니다
=> [Baekjoon-2839] jaehong

BOJ/seulah/3_week/설탕 배달.py, BOJ/seulah/3_week/주식.py
**언어 : 파이썬**
> 다음부턴 파일이 같이 올라가지 않도록 유의하겠습니닷..
------
각 테스트 케이스마다 입력받은 주식 가격을 기준으로 뒤에서부터 탐색하며, 가장 높은 판매 가격(max_price)을 기준으로 이익(max_profit)을 계산합니다.
**역순탐색을 하는 이유는?**
뒤에서부터 탐색하면, 미래의 최대 판매 가격을 미리 알 수 있기 때문에 효율적으로 계산할 수 있습니다.
뒤에서부터 주식 가격 확인하여 현재 가격(`price`)이 `max_price`보다 크다면 새로운 `max_price`로 갱신합니다.
` max_profit += max_price - price ` 으로 이익 계산하여 누적 값을 계산합니다
=> [Baekjoon-11501] seulah

BOJ/jaehong/3_week/설탕배달.java, BOJ/jaehong/3_week/주식.java, BOJ/jaehong/3_week/쿠키의신체측정.java
풀이 과정
1. 먼저, 맨 마지막 값을 max로 초기화를 해줍니다
2. 배열을 뒤에서 앞으로 탐색하며, 현재 값이 max보다 작다면 max - 현재 값을 이익으로 더해줍니다
3. 만약 현재값이 max보다 크다면, max를 갱신합니다
=> [Baekjoon-11501] Jaehong

BOJ/jaehong/3_week/설탕배달.java, BOJ/jaehong/3_week/쿠키의신체측정.java
문제 풀이
1. 이중 for문을 통해서 심장을 먼저 찾습니다. "*" 모양으로 십자가를 이루는 지점
2. 찾은 심장은 heartRow와 heartCol을 통해 위치를 특정합니다
3. 심장을 기준으로 for문을 통해서 각각 왼팔, 오른팔, 허리, 왼다리, 오른다리를 찾습니다.
=> [Baekjoon-20125] 타임어택 문제 풀이

BOJ/jeongbeen/3_week/쿠키의_신체_측정.java
for문으로 탐색하며 가장 먼저 쿠키의 신체 일부??가 나오면 머리 라고 생각했습니다.
심장은 그 바로 아래 있는 좌표를 출력하였고,
왼쪽팔, 오른쪽팔, 허리를 각각 탐색하면서 길이를 측정하고 출력하였습니다.
왼다리, 오른다리는 허리가 끝나는 지점으로부터 각각 대각선 왼쪽, 오른쪽부터 시작합니다.
마찬가지로 아래까지 탐색하여 길이를 출력하였습니다.
=> [Baekjoon-20125] 타임어택 문제풀이

BOJ/seulah/3_week/쿠키의 신체 측정.py
우선 실패했던 이유는 이중 for문에서 외부루프를 중단하는 코드를 작성하지 않아 발생하였고
이전 코드는 뭔지 모르겠어서
```
for i in range(N):
for j in range(N):
if cookie[i][j] == '*':
heart_x, heart_y = i + 1, j
break
else:
continue
break
```
이렇게 바꿔주어 외부루프를 중단하는 코드를 완성했습니다.
배열에서 처음으로 '*'이 나타나는 위치인 쿠키의 머리 부분을 기준으로 하여 바로 아래 행에 위치한 심장의 위치를 찾아 인덱스 값을 heart_x와 heart_y에 각각의 대입하였습니다.
심장을 기준으로 왼쪽/오른쪽 쿠키의 팔을 잘라 ^^.. `count` 함수로 *의 개수를 세어 구현했습니다
심장 바로 아래에서부터 시작해, 허리를 따라 세로로 '*'이 얼마나 연속되는지 확인합니다.
허리 끝 아래부터 왼쪽 다리(heart_y - 1)와 오른쪽 다리(heart_y + 1)를 각각 탐색하여 *의 개수를 세었습니다
=> [Baekjoon-11501] 타임어택_쿠키의 신체 측정

BOJ/minji/3_week/쿠키의 신체 측정.py
- 문제 풀이 방법
body size를 2차원 배열로 입력 받는다.
머리 -> 심장 -> 왼팔, 오른팔 -> 허리 -> 왼 다리, 오른 다리 순서로 찾는다.
- 머리
2차원 배열을 탐색하며 가장 먼저 *이 나온 위치를 머리의 위치로 판단한다.
- 심장
머리 기준으로 한 칸 밑을 심장의 위치로 판단한다.
- 왼팔, 오른 팔
심장을 기준으로 왼쪽, 오른쪽의 * 개수를 센다.
-허리
심장 밑을 기준으로 *이 하나인 행의 수를 센다.
-다리 
허리 밑을 기준으로 허리의 x축의 -1(왼쪽), +1(오른쪽) 의 값이 *인 개수를 센다.
각 단계마다 계산이 끝나 불필요한 부분은 슬라이싱 하여 효율적으로 처리하였다.
=> [Baekjoon-20125] 타임어택_문제풀이

BOJ/yein/4_week/최소 힙.py
**입력값 및 변수 설명**
`N` 에 입력받을 숫자 개수를 받고, `num`으로 입력 받아 `arr` 에 저장했습니다.
0 이외의 입력을 받으면 arr의 맨 끝에 값을 추가한 뒤 `heapify()` 사용자 정의 함수를 실행하고,
0을 입력 받아 배열에서 값을 삭제할 때는 `downHeap()` 사용자 정의 함수를 실행하도록 하였습니다.
**문제풀이 방식**
최소 힙의 기본적인 구현 방식을 따랐습니다.
값을 추가할 때는 힙의 가장 마지막에 값을 추가한 후 Up-heap (제 코드에서는 heapify() 함수로 구현) 과정을 거치고,
값을 삭제할 때는 루트 노드를 삭제하고 마지막 값을 끌어와 Down-heap 과정을 거치는 방식을 사용하였습니다.
개념이나 수도코드로만 보던 걸 실제로 구현해보니 생각보다 인덱스 관리하기가 어려웠습니다...ㅇ<-<
근데... 구현 자체보다, 시간 초과를 해결하지 못해 따로 찾아보고 해결하게 되었습니다.
파이썬의 `input()` 보다 `sys.stdin.readline()` (import sys 필수) 가 더 빠르다고 해서 바꿨더니 바로 풀리더라구요.
근데 힙 구현 자체의 문제가 있었을 수도 있는데 야매로 해결한 기분이라 찜찜합니다... 여러분의 (특히 파이썬) 코드가 너무 궁금해요...
=> [Baekjoon-1927] yein

BOJ/jeongbeen/4_week/분수찾기.java
고개를 조금 돌리고 보면 삼각형입니다. 인정하시죠?
.
.
.
처음을 1단계, 그다음을 2단게.... n 단계로 하겠습니다.
같은 단계에서 분수의 분자 분모의 합은 같습니다.
1, 2, 3,.... n 을 더하면서 X가 몇 단계에 있는지 탐색합니다.
해당 단계에서 X가 될 때 까지 탐색합니다.
단, 2n단계에서는 오른쪽부터 탐색하고, 2n-1단계에서는 왼쪽부터 탐색합니다.
값을 찾으면 반환합시다.
=> [Baekjoon-1193] jeongbeen

BOJ/jeongbeen/4_week/최소_힙.java
우선순위 큐(Priority Queue)를 하나 선언합니다.
우선순위 큐는 값을 넣고 뺄 때 가장 우선순위의 값을 반환합니다.
0이 아닐 때 값을 큐에 넣습니다.
0일때,
- queue가 empty라면 0을 출력합니다.
- empty가 아니라면 poll 한 값을 출력합니다. poll은 가장 우선순위의 값을 반환하고 큐에서 제거하는 메서드입니다.
끝~
=> [Baekjoon-1927] jeongbeen

BOJ/jihoon/4week/분수찾기.cpp
1193 문제는 수학 문제입니다.
각 대각선마다 +1 +2 +3 씩 개수가 증가합니다. 따라서  초기 count를 1로 설정한 뒤에 X에서 count를 빼고 ++count한 값을 또 빼고 반복하며, X가 0이하가 될 때, 몇 번째 대각선인지 알 수 있습니다.
예를 들어, count가 5라면 5번째 대각선입니다. 그리고 count가 짝수면 1 / count 스타트로 시작하고, 홀수면 count / 1 스타트 하므로 조건문으로 출력 형식을 설정합니다.
출력문은 짝수인 경우, count + X << "/" << 1 - X 이고, 홀수인 경우, 1 - X << "/" << count + X 입니다.
=> [Baekjoon-1193] jihoon

BOJ/seulah/4_week/최소 힙.py
> 언어 : 파이썬
처음엔 최소 힙이라는 문제 이름을 보고도 익숙하지 않아 호오옥시나 하는 마음에 리스트로 정렬해서 풀어봤는데
가차없이 시간초과가 나더군요...😅
그래서 파이썬에서 최소 힙을 사용하는 문법 한 번 스윽 보니 파이썬에서는 heapq모듈을 사용하면 리스트를 최소 힙으로 사용할 수 있어 기존 리스트로 구현한 코드에서 자료구조만 heapq로 바꿔주면 되어 쉽게 풀렸습니다.
근데 힙을 적용 했는데도 시간 초과가 나서 알아보니  Python I/O은 좀 느려서 sys.stdin을 사용해주니 해결되었습니다.
앞으로는 sys.stdin을 쓰는 습관을 들여야겠습니다! ! !
=> [Baekjoon-1927] seulah

BOJ/jaehong/4_week/최소힙.java
자바의 최소 힙 자료구조 PriorityQueue로 구현했습니다.
1. for문을 통해서 N번의 입력을 처리하며 x의 값을 확인합니다
2. minHeap이 비어있으면 0을 출력하고, 그렇지 않으면 poll()을 통해서 최솟값을 출력하고 제거합니다
3. 그 이외에 0보다 큰 경우는 add(x)를 통해 최소 힙에 추가합니다
=> [Baekjoon-1927] jaehong

BOJ/minji/4_week/분수찾기.py
배열을 지그재그 순서에 맞춰 보기 쉽게 정리하면 다음과 같다.
1/1
1/2, 2/1
3/1, 2/2, 1/3
1/4, 2/3, 3/2/, 4/1
...
각 행의 시작점이 되는 인덱스는 1, 2, 4, 7, 11 ... 이다.
주어진 수 x를 넘지 않는 수열에서 가장 큰 수를 찾고, 그 수가 수열에서 몇 번째 위치인지를 함께 반환한다.
짝수행에서는 분자는 1씩 증가, 분모는 1씩 감소
홀수행에서는 분자는 1씩 감소, 분모는 1식 증가한다.
=> [Baekjoon-1193] minji

BOJ/minji/4_week/최소_힙.py
파이썬에서 제공하는 힙 모듈 사용
- 힙에 값 추가
heapq.heappush(heap, item)
- 힙에서 최소값 제거 및 반환
heapq.heappop(heap)
* 참고
sys.stdin.readline을 사용하여 입력을 받으면 input()보다 빠르게 여러 줄의 입력을 받을 수 있어 시간초과를 방지하는 데 유리함
=> [Baekjoon-1927] minji

BOJ/seulah/4_week/분수찾기.py
엄...제가 내고 제가 못 풀었습니다. 대충 보고 쉬워 보이길래 골랏는데 생각보다 아주 힘들었습니다..
제가 수학을 못하는걸까요..? 구현을 못하는걸까요 ㅎ하핳
다른 글 참고하며 공부한다는 마음으로 정리하면서 풀었습니다..!
풀이는 사진으로 업로드 하겠습니다! (대충써서 글씨는 양해 부탁드립니다ㅎ)
=> [Baekjoon-1193] seulah

BOJ/yein/4_week/분수 찾기.py
**입력값 및 변수 설명**
N에 몇 번째 분수를 반환할지 입력 받습니다. sys... 뭐더라.. 안외워져서 활용 실패..
**문제풀이 방식**
대각선으로 봤을 때 첫째 줄엔 1개, 둘째 줄엔 2개, 셋째 줄엔 3개의 원소가 들어갑니다.
등차수열로 어찌저찌 계산하는 것보다 일일이 빼보면서 비교해봤는데, 시간초과가 안 나서 다행
음수가 되는 순간이, 원하는 분수가 있는 그 줄을 찾은 것이고,
다시 양수로 복구해준 뒤에 남은 숫자가 그 줄에서 몇 번째 분수인지를 나타내는 것입니다!
홀수개일 때는 우상향, 짝수개일때는 반대 방향으로 진행되기에 조건문으로 각각 계산했습니다.
푸는 방법을 구상하며 풀다보니... 더하면 될 걸 1씩 빼버렸지만...?! 다행히 시간초과는 발생하지 않아서 끝!
=> [Baekjoon-1193] yein

BOJ/jaehong/4_week/분수찾기.java, BOJ/jaehong/4_week/최소힙.java
이 문제가 더 어렵네요
1. while문을 사용해 X가 속한 대각선 n을 찾기
2. 해당 대각선에서 몇 번째(num)인지 찾기
3. num = X - (n-1) * n / 2 (이전 대각선까지의 합을 뺀 값)
4. 대각선이 짝수(n % 2 == 0)냐 홀수(n % 2 == 1)냐에 따라 분수 계산
- 짝수 대각선: top = num, bottom = n - num + 1
- 홀수 대각선: top = n - num + 1, bottom = num
=> [Baekjoon-1193] jaehong

BOJ/jeongbeen/4_week/진우의_달_여행_Small.java
이와 같은 dp 배열을 이용하여 이전 최솟값을 저장하는 방식으로 문제를 해결하였습니다.
근데 항상 문제 조건을 잘 보지 않는 습관이 있는데, 배열의 최대 크기가 7x7인줄 알았더라면 브루트 포스로 해결해도 괜찮았을 것 같습니다.
=> [Baekjoon-17484] 타임어택 문제풀이

BOJ/jaehong/4_week/진수의달여행.java
1. arr[n][m]로 지도에 적힌 비용을 저장합니다.
2. dp[n][m][3] : dp[i][j][d]는 (i,j) 위치에 d 방향으로 도착했을 때의 최소 비용을 저장하는 3차원 배열을 정의합니다
3. 그리고 모든 dp를 Integer max값으로 초기화합니다
Dp 테이블 갱신
1. i번째 행의 j번째 열로 이동할 때, dp값을 갱신합니다
2. 이후 모든 가능한 이동을 고려해서 최소 비용을 계산합니다
3. 마지막 행의 모든 dp 값 중 최소값을 찾아 출력합니다
=> [Beakjoon-17484] 타임어택 문제풀이

BOJ/jeongbeen/5_week/카드2.java
Queue를 이용한 간단한 문제입니다.
Java에서는 LinkedList가 Queue의 구현체라 LinkedList를 Queue처럼 사용했습니다.
queue에 카드들을 다 add한 이후, queue의 크기가 1이 될 때까지
1. poll을 하고
2. 한번 더 poll한 값을 queue에 add합니다.
남아있는 하나의 카드를 출력합니다.
=> [Baekjoon-2164] jeongbeen

BOJ/jeongbeen/5_week/회의실_배정.java
생각하는 시간은 오래 걸렸지만 구현은 간단한 그리디 문제입니다.
기본적인 구현 방법은 회의가 끝나는 시간이 가장 빠른 순으로 정렬하고, 끝나는 시간이 같다면 시작 시간이 빠른 순으로 정렬하여 현재 가능한 회의라면 진행하는 방식입니다.
이를 위해 Queue를 사용하였고, queue에 넣기 전에 ArrayList에서 끝나는 시간순으로 정렬하고, 시작 시간 순으로 추가로 정렬하였습니다.
가능한 회의라면 해당 회의를 진행하고, 회의 횟수를 1 증가시키고 끝나는 시간을 해당 회의의 끝나는 시간으로 갱신합니다.
불가능한 회의라면 queue에서 poll합니다.
끝~
=> [Baekjoon-1931] jeongbeen

BOJ/seulah/5_week/카드2.py
처음에 list로 풀었는데 list.pop(0)을 사용하면 O(N) 연산이 발생해서 시간초과가 났습니다.
그래서 메모리 상에서 앞 부분만 이동하여 O(1)로 접근 가능한 deque를 사용하여 해결하였습니다!
=> [Baekjoon-2164] seulah

BOJ/seulah/5_week/카드2.py, BOJ/seulah/5_week/회의실 배정.py
제가 옛날에 한 번 이 문제를 풀었었더라구요. 그치만 초면인 마냥 한참을 헤맸습니다....참고도 했구요,,,하하
우선은 처음에는 시간을 시작시간 기준으로 하고 시작시간이 같으면 종료시간을 기준으로 정렬을 했었습니다.
(람다를 사용해서 정렬하는 것 참고했습니다..)
하지만 그렇게 접근하는 것은 틀렸고, 회의 시간을 최대로 하기 위해서는 종료시간을 먼저 기준으로 정렬하고 종료시간이 같다면 시작시간을 기준으로 해야합니다. 그래야 짧게짧게 회의를 많이 할 수 있으니까요 
그러고 나서 정렬된 시간들을 시작시간과 종료시간으로 분류하여 현재 종료시간보다 다음 시작시간이 크거나 같으면 카운팅 하도록 하였습니다.
이때 또 실수한게 각 시작시간과 종료시간을 start와 end로 각각 받으면 언패킹이 되는건데 바보같이 이중리스트니까 두 번 풀어야징하다가 시간을 날렸읍니다.
=> [Baekjoon-1931] seulah

BOJ/jaehong/5_week/카드2.js
이번에는 js로 문제를 풀었습니다.
처음에는 짝수번째 인덱스는 존재하지 않는다라는 점에서
filter()함수로 짝수번째 인덱스를 전부 제거하고, 남은 나머지 배열 요소들을 거꾸로 뒤집고의 과정을
반복해서 접근해보려했지만, 틀렸다고 나와서 그냥 정석으로 접근했습니다
Q 배열로 초기화를 하고,
while문을 돌며 짝수 인덱스는 스킵하고, 홀수 인덱스는 배열 가장뒤에 추가하는 과정을 반복해서.
최종적으로 마지막에 남은 카드 번호를 반환합니다
=> [Beakjoon-2164] jaehong

BOJ/yein/6_week/회의실 배정.py
**<입력값 및 변수>**
`N`은 회의 개수를 담는 정수,
`arr`는 입력 받은 [회의시작시간, 회의종료시간] 배열을 가진 배열입니다.
**<문제풀이>**
삽입정렬, 버블정렬 등 직접 몇 가지 정렬을 수행하였으나 (주석처리된 부분은 하다 망한 부분....) 시간초과가 발생하였습니다.
아시다시피, 삽입 정렬, 버블 정렬, 선택 정렬 모두 최악의 경우 O(N^2)의 복잡도를 가집니다.
퀵정렬, 힙정렬 같은 정렬 방식이 생각이 났으나... 핸드메이드로 하자니 너무 막막해서... `.sort` 함수를 이용하였습니다.
`sort` 내장 함수는 성능도 O(NlogN)을 보장해주고, key값을 이용해 이차원 배열 등도 배열을 쉽게 수행할 수 있습니다.
정렬 이후의 진행 방식은, 회의시간/수강신청 문제의 일반적인 풀이법처럼 풀었습니다.
종료 시간이 빠른 것부터 차곡차곡 쌓아 가면 정답을 얻을 수 있습니다.
=> [Baekjoon-1931] yein

BOJ/jihoon/5week/카드2.cpp
2164 문제는 큐를 사용하는 간단한 문제입니다.
문제 그대로 행해주면 되는데, 카드를 순서대로 큐에 모두 넣고 첫 장은 버리고 다음 장은 pop 한 뒤, 큐에 다시 넣습니다.
이 행동을 큐에 데이터가 하나만 남을 때까지 반복하고, 하나만 남는 숫자를 출력하면 됩니다.
=> [Baekjoon-2164] jihoon

BOJ/yein/6_week/카드2.py
** <입력값 및 변수> **
`N`는 제일 위 카드의 번호입니다.
`arr`는 숫자가 든 덱(deque)입니다.
** <문제풀이> **
파이썬의 deque 라이브러리를 활용했습니다.
queue와 비슷하지만 앞 쪽에서도 삽입, 삭제가 빠르게 수행될 수 있는 자료구조입니다.
한 번은 버리고, 한 번은 앞으로 보내는(이때, 앞으로 보내는 것은 뒤에서 없앤 것을 앞에 더해줌) 방식으로, 문제풀이 자체는 문제에서 시키는 그대로 풀 수 있었습니다!
=> [Baekjoon-2164] yein

BOJ/jaehong/5_week/카드2.js, BOJ/jaehong/5_week/회의실배정.js
생각보다 문제가 쉬웠던 것 같네요
일단 회의가 끝나는 시간 기준으로 정렬을 합니다.
끝나는 시간이 같으면 시작 시간으로 정렬하게되고,
그 이후에 회의가 끝나는 시간과 시작하는 시간을 비교해서 선택하고,
endtime을 갱신해주면서 count를 증가시킵니다!
=> [Baekjoon-1931] jaehong

BOJ/jeongbeen/5_week/햄버거_분배.java
좀전에 그리디 문제를 봐서 그런지, 조금 쉽게 보였습니다.
길이가 N인 배열을 생성하여, 사람이라면 0, 햄버거라면 1로 입력받습니다.
왼쪽부터 배열을 탐색하면서, 사람이라면,
- 자신의 위치에서 왼쪽에서 K만큼부터 오른쪽 K까지 햄버거를 탐색합니다.
- 햄버거를 찾았다면 해당 햄버거는 -1로 바꾸고, 답을 하나 증가시킵니다.
- 반복
=> [Baekjoon-19941] 타임어택 문제풀이

BOJ/yein/6_week/햄버거 분배.py
**입력값 및 변수**
`N` 과 `K`에 사람 및 햄버거의 수, 거리를 입력 받습니다.
`arr`에 문자열을 입력받아 리스트로 변환했습니다.
`cnt`에 반환할 정답을 저장할 것입니다.
**문제풀이**
앞에서부터 돌면서, 사람('P')이 나오면 자신 주변으로 햄버거를 찾습니다.
가능한 한 앞쪽에 있는 걸 먹어야 뒷 사람이 먹을 가능성이 높아지므로, 앞에서부터 탐색합니다.
이때, 인덱스 관리를 위해 min과 max를 사용해 봤는데... 오 이거 쫌... 제법 괜찮은 방법 같아요!ㅎㅎ 뻔한 방법일수도 있지만ㅎㅎㅎ...
(특히... 파이썬의 음수 인덱싱을 까먹었다가 오류를 많이 겪었는데... 꽤 괜찮은 방법 같습니다...)
=> [Baekjoon-19941] 타임어택 문제 풀이

BOJ/jihoon/6week/계단_오르기.cpp
2579 문제는 다이나믹 프로그래밍을 이용해서 풀어야 하는 문제입니다.
bottom-up 방식으로 0번 인덱스부터 구하고자 하는 n번 인덱스까지 순차적으로 쌓습니다.
어떻게 n번째 위치의 계단에 도달했을 때의 최댓값을 구하지라고 생각하자면, 만약 n번째 계단을 밟는다면, 경우의 수는 두가지가 나옵니다.
1. n-2번째를 무조건 밟고 n-1을 건너뛴 다음 n번째를 밟는다.
2. n-3번째를 무조건 밟고 n-1과 n번째를 밟는다.
따라서 1번과 2번 중 최대값이 되는 경우의 수를 찾으면 된다. 그리고 1번과 2번의 n-2번과 n-3번의 값은 해당 지점까지의 최댓값이다.
이를 수식화하면 `dp[n] = max(dp[n-2], dp[n-3] + score[n-1]) + score[n] (n>=3)` 이 되게 된다.
n은 3이상일 때 위 수식을 만족하므로 직접 3번 인덱스까지 초기화하고 for문을 통해 dp[n]을 구하게 되면 정답이다.
=> [Baekjoon-2579] jihoon

BOJ/jihoon/6week/컨베이어_벨트_위의_로봇.cpp
20055 문제는 알고리즘 기법을 사용하는 문제보다는 조건에 맞게 착실히 구현하면 되는 구현 문제입니다.
중요했던 두 가지는
1. start, end 포인터
2. 내구도 감소시 0 체크
였습니다.
조건 정리는 아래와 같이 했습니다.
조건1: 벨트와 로봇 회전
조건2: 로봇 한칸 이동 or 정지 => 이동하려는 칸에 로봇 x & 이동 칸의 내구도 > 0
조건3: 올리는 위치 칸 내구도 > 0 이면 로봇 올리기
조건4: 내구도 0인 칸 개수 >= K 면 종료
=> 종료되었을 때, level 출력
주의할 점은 조건1은 뒤로 회전하는 것이고, 조건2는 end 지점부터 로봇을 이동하는 것, 로봇을 올릴 때마다 내구도 감소 및 zeroCnt 증가였습니다.
이것을 모두 수행하면 풀리는 문제입니다.
=> [Baekjoon-20055] jihoon

BOJ/seulah/6_week/계단 오르기.py
마지막 계단은 무조건 밟아야하므로 도착지부터 접근합니다
dp[i] : i 번째 계단까지 올라갔을 때 얻을 수 있는 최대 점수
i번째 계단에 도착하는 경우는 2가지입니다.
1) 2칸 전에 있던 계단에서 한 번에 2칸 올라온 경우
i-2번째 계단에서 i번째 계단으로 점프 
=> dp[i-2] + stairs[i]
2) 3칸 전에 있던 계단에서 1칸 + 1칸 올라온 경우
i-3번째 계단 → i-1번째 계단 → i번째 계단
=> dp[i-3] + stairs[i-1]+stairs[i]
점화식
dp[i] = max(dp[i-2] + stairs[i], dp[i-3] + stairs[i-1] + stairs[i])
+) 처음에 N이 1,2일 때를 고려해주지않아 계속 런타임 에러가 발생했었습니다.. 😅
=> [Baekjoon-2579] seulah

BOJ/seulah/6_week/컨베이어 벨트 위의 로봇.py
우선 문제 자체를 이해하는데 좀 오래걸렸고,,ㅎ
벨트와 로봇을 회전 시키는 방법으로 처음엔 pop/push를 사용했었는데 아무리 생각해도 좀 너무 비효율적이라
찾아보니 파이썬은 deque을 사용했을 때 rotate라는 아주 좋은 함수를 쓸 수 있더군요!!! 하하.. 그래서 참고해서 적용했습니다,,
나머진 그냥 적힌대로 구현했습니다
=> [Baekjoon-20055] seulah

BOJ/jaehong/6_week/계단오르기.js
이 문제의 핵심은 단순히 점수를 합산하는 것이 아니라, 1단 점프와 2단 점프의 규칙을 고려해야합니다
1. n-2번 칸에서 2단 점프는 -> 제한 없음
2. n-1번 칸에서 1단 점프 -> 1단 점프를 연속 2번 하면 안됩니다
이를 해결하기 위해서 n-3번 칸에서 2단 점프 후 n-1에서 1단 점프를 하면 해결됩니다
```bash
dp[i] = Math.max(dp[i - 3] + input[i - 1], dp[i - 2]) + input[i];
```
=> [Baekjoon-2579] jaehong

BOJ/minji/6_week/계단 오르기.py
다이나믹 프로그래밍을 사용하여 문제를 해결했습니다.
dp배열을 정의하여 i번째 계단까지 올랐을 때의 최대 점수를 저장하였습니다.
첫 번째, 두 번째 계단은 초기조건으로 처리하였고, 세 번째 계단부터는 이전 두개의 계단을 건너뛰거나, 두 계단을 연속으로 밟는 경우를 나누어 계산하여 최댓값을 갱신하였습니다.
=> [Baekjoon-2579] minji

BOJ/jihoon/7week/빗물.cpp
14719 문제는 구현 문제입니다.
빗물을 어떻게 체크할지만 생각하면 간단하게 풀 수 있는 문제입니다.
먼저 2차원 배열로 블록이 어느 위치에 있는지 모두 입력합니다.
그리고 최하단 행부터 탐색을 시작하는데, 시작 블록을 확인하고 비어있는 지점을 지나 다시 블록을 마주하면 끝 블록으로 판단해 끝 블록 - 시작 블록 - 1을 하여 빗물의 값을 계산하고, 다시 끝 블록 위치를 시작 블록 위치로 지정하며 반복합니다.
이 작업을 최하단 행부터 최상단 행까지 반복해주면 풀리는 문제입니다.
=> [Baekjoon-14719] jihoon

BOJ/minji/6_week/컨베이어_벨트_위의_로봇.py
문제를 이해하는 게 더 어려웠던 문제였습니다. 
풀이 방법
1. 벨트 회전
벨트와 로봇을 한 칸씩 회전, 회전 후 n번째 칸에 있는 로봇 제거
2. 로봇 이동
뒤에서부터 이동 가능하면 한 칸 전진(내구도 감소)
3. 로봇 올리기
0번째 칸 내구도가 1이상이고 로봇이 없으면 올림
4. 종료 조건
내구도 0인 칸이 k개 이상이면 종료  
=> turn_count 변수를 증가시키며 위 과정을 반복한다.
=> [Baekjoon-20055] minji

BOJ/jaehong/6_week/컨베이어 벨트 위의 로봇.js, BOJ/jaehong/7_week/빗물.js
왼쪽에 있는 블록들의 최대 높이와 오른쪽에 있는 블록들의 최대 높이를 구합니다
이 두 값 중 작은 값이 해당 위치에서 물이 차오를 수 있는 최대 높이가 됩니다
그 이후 모든 칸의 값을 비교하며 더해 최종 답을 출력합니다
=> [Baekjoon-14719] jaehong

BOJ/jaehong/6_week/컨베이어 벨트 위의 로봇.js, BOJ/jaehong/7_week/빗물.js, BOJ/jaehong/7_week/좋다.js
일단 사용자의 입력값을 오름차순으로 정렬하고, for문을 돌며, 
각각의 값의 왼쪽과 오른쪽의 포인터를 이동시키면 count를 증가시킵니다
left + right가 target보다 크다면 right인덱스 값을 감소시키고, 작다면 left 인덱스값을 증가시키는 방식으로 처리했습니다
=> [Baekjoon-1253] jaehong

BOJ/minji/6_week/1, 2, 3 더하기 4.py
dp로 문제를 해결했습니다.
숫자 N을 만들 때 마지막에 1을 더한 경우, 2를 더한 경우, 3으로 나눌 수 있습니다.
ex) 4를 만드는 방법
- (3을 만드는 방법의 개수) + 1
- (2를 만드는 방법의 개수) + 2
- (1을 만드는 방법의 개수) + 3
=> 4를 만드는 방법 = 3 만드는 방법 + 2 만드는 방법 + 1 만드는 방법
풀이방법
- 1만 사용하는 경우를 기본적으로 포함하기 위해 배열을 1로 초기화 합니다.
- for i in range(2, 10001):
dp[i] += dp[i-2]
-> i에서 2을 빼면 i를 만들 수 있는 방법을 추가됨
- for i in range(3, 10001):
dp[i] += dp[i-3]
-> i에서 3을 빼면 i를 만들 수 있는 방법을 추가됨
=> [Baekjoon-15989] 타임어택 문제 풀이

BOJ/seulah/6_week/1, 2, 3 더하기 4.py
> 우선 1,2,3 더하기 실버 문제를 풀어봤기 때문에 dp로 접근하는 것은 알고있었고, 중복을 허용하지 않는다는 점만 달라 최대한 비슷하게 접근하려고 했었는데 알듯말듯 규칙을 찾기 너무 어렵더라구요...한 세월을 보내고 결국 참고하였습니다...................
기존 1,2,3 더하기 문제(백준 9095번)와 다르게, 순서를 고려하지 않기 위해 숫자를 "**작은 것부터 차례로 추가하는 방식**"을 사용해야 하는 것이 중요한데욥. 1 → 2 → 3 순으로 점점 더 큰 숫자를 추가하면서 만들 수 있는 경우의 수를 구하는 방식으로 풀어야 합니다.
**1️⃣ 1을 사용해서 N을 만드는 경우**
모든 수는 1만 사용해서 값을 만드는 경우를 포함하기 때문에 dp 배열을 초기값 1으로 설정합니다.
`dp[5] = 1`
**2️⃣ 2를 사용해서 N을 만드는 경우**
dp[i-2]를 만들 수 있는 경우에 +2를 추가하면 dp[i]를 만들 수 있음.
`dp[5] += dp[3]`
**3️⃣ 3을 사용해서 N을 만드는 경우**
→ dp[i]에 dp[i-3]를 더해준다 = 마찬가지로 i-3을 만드는 방법에 +3을 붙이면 i가 된다!
는 방식으로 접근합니다.
`dp[5] += dp[2]`
=> [Baekjoon-15989] 타임어택 문제풀이

BOJ/minji/7_week/빗물.py
i번째 블록 위에 물이 고이려면 그 위치의 왼쪽과 오른쪽에서 가장 높은 블록을 찾아야 합니다.
start, end 변수에 i의 왼쪽에서 가장 높은 블록의 높이, i의 오른쪽에서 가장 높은 블록의 높이를 구해서 저장합니다.
i위치에서 물이 고일 수 있는 높이는 왼쪽과 오른쪽의 최대 높이 중 작은 값(h)이 기준이 됩니다. 
block[i] 보다 h가 크다면, 물이 h-block[i]만큼 고입니다.
모든 블록에 대하여 계산하면 물이 고이는 총량을 계산할 수 있습니다.
=> [Baekjoon-14719] minji

BOJ/seulah/7_week/빗물.py
1️⃣ 가장 높은 벽(nw_idx)을 기준으로 왼쪽과 오른쪽을 나눔
2️⃣ 왼쪽부터 nw_idx까지 탐색하면서 left_max를 유지하며 빗물 계산
3️⃣ 오른쪽부터 nw_idx까지 탐색하면서 right_max를 유지하며 빗물 계산
처음엔 그냥 고정된 max값을 구했는데 
left_max / right_max는 계속 갱신되면서 누적 빗물 계산에 영향을 줘야 해서 좀 헤맸고..
오히려 너무 복잡하게 생각해서 시간이 오래걸렸읍니다..
=> [Baekjoon-14719] seulah

BOJ/yein/8_week/빗물.py, BOJ/yein/8_week/좋다.py
엇... 뭔가 제가 브랜치를 잘 못 만든 것 같은데요.... 웁쓰
당장은 무슨 일인지 잘 모르겠습니다. 미리 죄송합니다..........
**입력값 및 변수**
직사각형의 높이와 너비를 각각 `h`, `w` 에 받습니다.
가로로 이동하면서 벽들의 높이를 `block`에 받습니다.
`left_idx`, `right_idx`로 현재 가리키고 있는 위치를 나타내고, `left_wall`과 `right_wall`을 이용해 현재 가리키고 있는 위치의 벽 높이를나타냈습니다. 처음에는 코드의 길이나 가독성을 위해 굳이 따로 선언했는데, 문제 풀이 중에는 이전 위치의 벽 높이를 나타내는 데에 사용되었습니다.
`water_sum` 반환할 값입니다.
**문제풀이 방식**
1253번 문제와 마찬가지로, `투 포인터` 방식을 사용해 접근했습니다.
왼쪽 끝과 오른쪽 끝에서 접근해가며 문제를 풉니다. 두 포인터가 교차되면 종료합니다.
`water_sum`에 더해지는 물의 양은 해당 위치에서 물을 채울 수 있는 공간의 높이를 의미합니다.
보다 높은 벽이 나타나면 벽의 높이를 업데이트하고, 이전 벽이 더 높다면 물을 채우지 않습니다.
늦어서 죄송합니다ㅏ.
=> [Baekjoon-14719] yein

BOJ/seulah/7_week/좋다.py
처음엔 브루트포스 방식을 사용해서 시도했는데 삼중 for문이라 O(N^3)로 택도 없어서 다른 방법을 찾고 있었는데 여러분의 코드를 참고하여 투포인트라는 개념을 적용해보았습니다! 
결과적으로 정렬: O(N log N) + 투 포인터 탐색: O(N)) = O(N²) 정도로 시간 복잡도를 줄일 수 있었습니다.
시간복잡도에 대해 좀 더 고려해볼 수 있는 계기가 되었습니다.
=> [Baekjoon-1253] seulah

BOJ/seulah/7_week/지름길.py
> 결국 돌고 돌아 dp로....... 하지만 그 마저도 조금 참고하였습니다... ㅜㅡㅜ 
`dp[i]`:  출발점(0km)에서 i km까지 가는 최소 거리를 저장하는 배열 (= i km까지 도달하는 최단 거리)
dp 배열 초기 상태 : 기본적으로 1km씩 이동할 수 있으므로 `dp[i] = i`로 초기화
`dp[start] + length` : 지름길을 이용했을 경우
`dp[i-1]+1`: 지름길 적용한 길에서 다시 1km씩 이동
min을 사용하여 1km씩 이동한 경우와 비교하여 최단 거리 갱신
`dp [i] = min(dp[i], dp[i-1]+1)` : 지름길이 없다면 dp[i]와 dp[i-1]+1이 동일함
지름길을 적용했을 경우에는 적용한 dp[i]값으로 갱신
**(0 → 5, 2km) (3 → 6, 1km) 지름길**
`초기 dp 배열 dp = [0, 1, 2, 3, 4, 5, 6, 7]
`
**dp[i] 갱신 과정**
**✔️ i = 1 ~ 4 (기본 이동)**
```
dp[1] = min(dp[1], dp[0] + 1)  → dp[1] = min(1, 0 + 1) = 1
dp[2] = min(dp[2], dp[1] + 1)  → dp[2] = min(2, 1 + 1) = 2
dp[3] = min(dp[3], dp[2] + 1)  → dp[3] = min(3, 2 + 1) = 3
dp[4] = min(dp[4], dp[3] + 1)  → dp[4] = min(4, 3 + 1) = 4
```
아직 지름길이 없으므로 dp[i] = i 그대로 유지됨!
`dp = [0, 1, 2, 3, 4, 5, 6, …
=> [Baekjoon-1446] 타임어택 문제풀이

BOJ/jihoon/6week/좋다.cpp
1253번은 이분탐색으로 풀었습니다.
이분탐색은 정렬된 수에 적용할 수 있기 때문에, 먼저 입력 받은 수를 오름차순으로 정렬합니다.
그리고 각 인덱스를 for문으로 돌며 i번째 인덱스를 다른 두 수의 합으로 구할 수 있는지 확인하는 binarySearch() 메서드를 실행합니다.
binarySearch 메서드에서는 i번째 인덱스를 제외하고 다른 한 인덱스의 값을 기준으로 탐색을 시작합니다.
그리고 i와 j를 고정한 다음 arr[i] = arr[j] + arr[mid]를 만족하는 mid 인덱스를 구합니다.
그리고 0번 인덱스와 N-1 인덱스를 시작, 끝 인덱스로 설정하고 이분 탐색을 진행합니다. 이때 mid가 i나 j라면 시작 지점과 끝지점을 갱신해줍니다. mid가 i보다 작게 나온다면 시작 지점을 올려주고 그렇지 않다면 끝 지점을 내려줍니다.
그렇게 해서 arr[i] = arr[j] + arr[mid] 라면 true, arr[i] < arr[j] + arr[mid] 라면 끝지점 내리기, arr[i] > arr[j] + arr[mid] 라면 시작 지점 올리기를 하여 true가 나오면 goodCnt++를, false라면 추가하지 않으며 최종 개수를 구합니다.
---
다른 풀이를 보니 투포인터가 더 편한 것 같기는 합니다..
=> [Baekjoon-1253] jihoon

BOJ/minji/7_week/지름길.py
dp가 너무 어려워서 다른 방법으로 문제를 풀고 싶어서 다익스트라 알고리즘으로 해결하였습니다.
역시 쉽지 않았습니다..
다익스트라는 그래프에서 특정 시작 지점으로부터 다른 모든 지점까지의 최단 경로를 찾는 알고리즘입니다. 그리디 알고리즘의 일종으로 각 단계에서 현재까지 가장 짧은 경로를 선택하는 방식으로 작동합니다.
각 위치에서 다음 위치로 가는 경로를 기본 1로 설정하고 주어진 지름길을 그래프에 넣었습니다.
다익스트라 알고리즘 적용해서 우선순위 큐를 이용해 현재까지 도달한 지점에서 최소 비용을 갱신하면서 목적지까지의 최소 비용을 계산합니다. 각 지점에 대해 더 빠른 경로가 있다면 그 비용을 업데이트하는 방식으로 최단 경로를 구했습니다.
=> [Baekjoon-1446] 타임어택_문제풀이

BOJ/jeongbeen/7_week/빗물.java
늦게올려서 죄송합니다!!
최대 높이의 벽을 만날 때 까지 양쪽에서 탐색하며 더 높은 벽을 만나면 갱신해주고 그 전까지는 이전 최대 높이의 벽만큼 빗물을 추가시켜주었습니다.
이제야 다른분들 코드를 보았는데,  투포인터 방식도 좋은 것 같습니다!
=> [Baekjoon-14719] jeongbeen

BOJ/jeongbeen/7_week/좋다1.java
처음에는 단순하게 풀다가 자기 자신 제외 등 여러 문제가 생겼었습니다.
두 번째는 map을 사용해서 조합을 찾다가 메모리 초과가 발생했습니다...
결국 투 포인터로 접근을 했는데 빗물 문제와 마찬가지로 앞으로 이런 방법을 알고있어야 할 것 같습니다.
=> [Baekjoon-1253] jeongbeen

BOJ/jaehong/7_week/지름길.js, BOJ/jaehong/8_week/게으른 백곰.js
1차원 직선상에서 가장 많은 얼음을 먹을 수 있는 곳을 찾는 최적 위치 탐색 문제입니다. 일단 얼음 양동이 정보를 for문을 돌며 저장합니다. 그때마다 가장 큰 위치를 갱신해주고, 그리고 슬라이딩 윈도우 기법을 통해서 0~k 범위 내 얼음 합을 계산합니다.
그리고 슬라이딩 윈도우 이동을 통해 left를 제거하고, right를 추가하면서 windowSum을 갱신해줍니다
마지막으로 maxIce를 통해 최적의 위치를 찾는 식으로 풀었습니다.
=> [Baekjoon-10025] jaehong

BOJ/minji/8_week/게으른 백곰.py
슬라이딩 윈도우 방식으로 문제를 해결하였습니다. 
ice 배열 안에 위치에 따른 얼음의 수를 저장하였습니다. window_size = 2 * k + 1로 슬라이딩 윈도우의 크기를 설정하고, 반복문을 돌리며 왼쪽 값을 빼고, 오른쪽 값을 더하는 방식으로 구현하였습니다. 반복문이 돌 때마다 max_ice 값을 초기화해주며 최대 얼음양을 구하였습니다.
=> [Baekjoon-10025] minji

BOJ/yein/9_week/게으른 백곰.py
ㅠㅠ 상어초등학교 풀다가 업로드가 늦었네요. 죄송합니다...
상어초등학교를... 못 풀었어요.
`슬라이딩 윈도우` 방식으로 풀었습니다!
입력받은 정보를 통해, 최대 길이(거리)만큼 배열을 만들어주었습니다.
거기서부터는 전에 `블로그` 문제에서 했던 것처럼 슬라이딩 윈도우 방식으로 풀었습니다.
다만, 범위 설정이 조금 어려웠습니다....
=> [Baekjoon-10025] yein

BOJ/seulah/8_week/상어 초등학교.py
**1️⃣ 학생 자리 배치 과정 - 최적의 자리 찾기**
각 자리에서 상하좌우 방향을 탐색하면서 조건을 만족하는지 확인합니다.
자리 선정 기준은 우선 순위를 따져가며 진행합니다.
**🔹 (1순위) 좋아하는 친구가 가장 많이 인접한 자리 선택**
```
if prefer > max_prefer:
max_prefer = prefer
max_empty = empty
x, y = i, j
```
현재 탐색 중인 자리의 prefer 값(주변 좋아하는 친구 수)이 max_prefer보다 크다면,
더 많은 좋아하는 친구가 있는 자리이므로 무조건 갱신합니다.
따라서 max_prefer 값을 갱신하고, 최적의 (x, y) 위치를 업데이트합니다.
**🔹 (2순위) 좋아하는 친구 수가 같다면, 빈자리가 더 많은 곳 선택**
```
elif prefer == max_prefer:
if empty > max_empty:
max_empty = empty
x, y = i, j
```
만약 prefer 값이 기존 max_prefer 값과 같다면, 두 개 이상의 후보지가 존재하는 것이므로
이때는 주변 빈칸(empty) 개수를 비교하여, 더 넓은 공간이 있는 자리를 선택합니다. 
즉, empty 값이 더 큰 경우, max_empty 값을 갱신하고 (x, y)를 업데이트 합니다.
**🔹 (3순위) 빈자리 수도 같다면, 행 번호가 작은 곳을 우선 선택**
```
elif max_empty == empty:
if i < x:  # 행이 더 작은 곳을 선택
x , y = i, j
elif i == x and j < y:  # 행이 같다면 열이 더 …
```
=> [Baekjoon-21608] seulah

BOJ/jaehong/8_week/상어 초등학교.js
처음에 N × N 크기의 classroom을 0으로 초기화한 뒤, 입력받은 데이터를 바탕으로 각 학생마다 좋아하는 친구를 빠르게 찾을 수 있도록 Map 자료구조에 저장했습니다
이후 학생들이 차례대로 들어오면 교실의 모든 빈자리를 탐색하여 각 자리에서 다음 두 가지를 조사합니다.
- 인접한 칸에 좋아하는 친구가 몇 명 있는지(likeCount)
- 인접한 칸 중에 빈칸이 몇 개 있는지(emptyCount)
이 두 가지 값을 비교해 가장 좋은 자리를 결정합니다. 
이 조건에 따라 후보가 되는 자리들을 배열(bestPositions)에 넣고 정렬하여 최종 자리를 결정한 뒤 학생 번호를 기록합니다.
모든 학생이 자리를 잡고 나면, 이제 다시 한 번 각 학생을 확인하여 인접한 자리에 좋아하는 친구가 몇 명인지 세어 만족도를 계산하는 방식으로 접근했습니다
=> [Baekjoon-21608] jaehong

BOJ/minji/8_week/상어 초등학교.py
check_seat 라는 함수를 만들어서 좌표와 좋아하는 친구 리스트를 입력하면 좋아하는 친구의 수, 빈 자리 수를 리턴하도록 하였습니다. 
자리는 n*n이므로 모든 자리 (i, j)에 대해 check_seat 함수를 호출하여 친구 수, 빈자리 수를 계산하였습니다. best position, 최대 친구 수, 최대 빈자리 수를 -1로 초기화하여 최적의 자리의 기준을 설정했습니다. 
문제의 조건대로
-좋아하는 친구 수가 가장 많은 자리
-좋아하는 친구 수가 같으면 빈자리가 가장 많은 자리
-모두 같으면 행, 열이 가장 작은 자리를 택하도록 하였습니다. 
마지막으로  인접한 친구 수에 따라 만족도를 계산했습니다.
=> [Baekjoon-21608] minji

BOJ/jihoon/8week/상어_초등학교.cpp
21608 문제는 구현 문제입니다.
각 조건들에 맞게 데이터를 구성하고 판단하는 과정이 복잡해서 많이 오래 걸린 문제입니다...
처음에는 1조건을 판단 후, 2조건과 3조건을 판단하려 했는데, 1,2,3번 조건을 한번에 판단하는 것이 낫겠다고 생각했습니다.
이를 위해서 기존에는 좋아하는 학생 수로 나눠 pair로 행과 열을 넣었지만, for문을 줄이고
1. 각 학생 마다
2. 비어있는 자리에 대해서 (인접한 좋아하는 학생 수, 인접 빈칸 수, 행, 열) 의 값을 tuple로 저장
3. 커스텀 정렬을 통해서 (좋아하는 학생 좌석 내림차순 -> 인접 빈칸 수 내림차순 -> 행 오름차순 -> 열 오름차순)으로 정렬하여 0번 째 인덱스 값에 있는 행과 열에 해당하는 학생을 넣었습니다.
그리고 모든 자리가 채워진 후에는 각 위치에서 인접한 학생 수를 구하고 10의 cnt-1 제곱만큼 더해주며 만족도를 구하고 출력하며 해결했습니다.
=> [Baekjoon-21608] jihoon

BOJ/jihoon/9week/포도주_시식.cpp
2156 문제는 dp로 풀었습니다.
이 풀이에서는 2차원 배열을 사용하긴 했는데, 이후 다른 풀이를 보니 그냥 1차원 배열로 훨씬 간단하게 풀리는 문제더라구요.
제 풀이를 소개하자면, dp는 2차원 배열로 구성했고, 2차원 배열의 0번 인덱스는 현재 위치에서 안 마셨을 때 최댓값(dp[i][0]), 1번 인덱스는 마셨을 때 최댓값(dp[i][1]) 으로 설정하고자 했습니다.
1번 인덱스까지는 직접 초기화하고, 2번 인덱스부터는 점화식을 통해 값을 추가했습니다.
i번째에서 마시지 않는 경우, (이전 잔을 마셨을 때 최댓값 or 이전 잔을 마시지 않았을 때 최댓값) 의 max 값을 선택했습니다.
i번째에서 마시는 경우, (2번째 이전 잔을 마시지 않았을 때 & 이전 잔을 무조건 마실 때 or 이전 잔을 무조건 마시지 않을 때) 의 max 값을 선택했습니다.
이렇게 구성한 후 n번째 인덱스에서 마셨을 때와 마시지 않았을 때의 값 중 max 값을 출력하면 해결됩니다.
=> [Baekjoon-2156] jihoon

BOJ/jaehong/9_week/포도주 시식.js
dp[i]는 i번째 포두주 잔까지 고려했을때 최댓값 값을 의미합니다
점화식을 통해서 각각의 경우의 수의 최대값을 max를 통해서 추출해서 문제를 해결할 수 있었습니다
=> [Baekjoon-2156] jaehong

BOJ/minji/9_week/포도주 시식.py
저번에 풀었던 계단 오르기 문제와 비슷한 문제였습니다.
마찬가지로 dp로 문제를 해결했습니다.
첫 번째 와인만 마시는 경우
->첫 번째 와인이 최댓값
두 번째 와인까지 마시는 경우
-> 와인 첫 번째 와인과 두 번째 와인을 모두 마시는 경우가 최댓값
세 번째 와인까지 마시는 경우
-> 첫 번째, 세 번째 와인을 마시는 경우
-> 두 번째, 세 번째 와인을 마시는 경우
-> 두 번째 와인을 마시는 경우
세 가지 경우 중 가장 큰 값에 해당합니다.
나머지 경우(i 번째 와인까지 마시는 경우)도 마찬가지로
-> i-2, i // i-3, i-1, i // i-1 중 최댓값에 해당합니다.
dp[i] = max(dp[i-2] + wine[i], dp[i-3] + wine[i-1] + wine[i], dp[i-1])
=> [Baekjoon-2156] minji

BOJ/seulah/9_week/포도주 시식.py
wine 맨 앞에 0인 더미 값을 넣어줘 dp와 인덱스를 맞춰줍니다. 
점화식의 경우 n이 3일 때부터는 연속된 잔을 선택하지 않아야하고, 현재 잔을 마시는 경우와 안 마시는 경우를 나누어 생각해야 합니다.
* 현재 잔을 마시지 않는 경우 : `dp[i] = dp[i-1]`
* 현재 잔을 마시는 경우: `dp[i-2]+wine[i], dp[i-3]+wine[i-1]+wine[i]`
```
dp[3] = max(dp[1] + wine[3], dp[2], dp[0]+wine[2]+wine[3])
dp[4] = max(dp[2] + wine[4], dp[3], dp[1]+wine[3]+wine[4])
```
`dp[i] = max(dp[i-2]+wine[i], dp[i-1], dp[i-3]+wine[i-1]+wine[i])`
=> [Baekjoon-2156] seulah

BOJ/jeongbeen/9_week/포도주_시식.java
DP로 해결하였습니다.
포도주를 연속으로 3개 마시면 안되기 때문에
dp[n-1], dp[n-2] + arr[n], dp[n-3] + arr[n-1] + arr[n] 중에 최댓값을 찾아 저장하였습니다.
=> [Baekjoon-2156] jeongbeen

BOJ/yein/9_week/포도주시식.py
다들,... 쉬우셨죠...!!!!
코테에서 쉬운 문제 나왔을 때 당황하시지 말라고 한번 골라봤습니다.
사실 농담이고 제가 그냥 dp를 너무 못해서......... 연습이 필요한 것 같아 낮은 티어 중에서 dp를 골라봤습니다.
아주 기본적인 `다이나믹 프로그래밍`  방식으로 풀었습니다.
이때, <두 개 연속 불가능>이 가장 중요한 조건이었습니다.
이제서야 깨달은 해법은...!! "먹지 않는다(포함하지 않는다)"의 경우, 직전까지의 선택을 신뢰할 수 있게 된다는 거였습니다!
원래는 dp 배열을 이용하면서도 최적해가 기본조건을 위반하지 않는지를 항상 헷갈렸었고 때려맞추는 느낌이 있었는데, 이제서야 좀 확신이 듭니다.
앞으로 더 어려운 문제에 또 도전해보겠습니다! 수고하셨습니다 :D!!!
=> [Baekjoon-2156] yein

BOJ/jeongbeen/9_week/스카이라인_쉬운거.java
Priority queue 를 사용해서 해결하였습니다.
pq의 peek한 값보다 현재 스카이라인이 높으면 pq에 해당 값을 넣습니다.
그렇지 않다면 현재 스카이라인 값보다 큰 값까지 pq에서 poll하면서 poll한 개수만큼 빌딩 개수를 늘립니다.
그러고도 pq값이 같은게 아니라 더 작은 값이 있다면, 현재 스카이라인 높이를 넣습니다.
=> [Baekjoon-1863] 타임어택 문제풀이

BOJ/seulah/9_week/스카이라인 쉬운거.py
**초기 생각**
```
import sys
input = sys.stdin.readline
N = int(input())
skylines = [list(map(int,input().split())) for _ in range(N)]
skylines.append([0,0])
prev_height = 0
building = 0
for x,y in skylines:
if y < prev_height:
building +=1
prev_height = y
print(building)
```
스택을 사용하지 않고 이전 고도보다 낮아지면 building +1 하는 방식 사용
—>답 6은 나왔지만 반례가 있어 틀렸었습니다!
> (2,3)지점의 종료 부분이 없으므로 계산을 할 수 없습니다.
* 스택에는 현재 유지되고 있는 건물의 높이들을 저장한다.
* y < stack[-1] (높이 감소) → 건물 개수 증가 + 이전 건물 제거
* y > stack[-1] (높이 증가) → 새로운 건물 시작
```
while stack and stack[-1] > y: # 다음 값이 더 작을 경우 => 건물 종료
stack.pop()
building +=1
```
while문으로 stack에 남아있는 값들을 다 처리해주면 종료지점이 없는 부분의 반례를 처리해줄 수 있습니다
> 쉽게 생각했는데...너무 쉽게 생각해버렸나봐요 ㅎ ㅜ..결국 또 혼자서 못풀고 참고해버렸읍니다...엉엉
=> [Baekjoon-1863] seulah

BOJ/seulah/10_week/단축키 지정.py, BOJ/seulah/10_week/타겟 넘버.py
[Programmers - 타겟 넘버]
> 제가 알고있던 dfs/bfs 문제와 사뭇 달랐고.. 오랜만에 그래프 문제이기도 했고 .....도대체 이걸 어떻게 그래프로 푸나 한참을 고민하다 ... 참고하였습니다. (주절주절) 갈 길이 한참 머네요 저능 ,,ㅎ
해당 문제는 BFS,DFS 둘 다 접근 가능한 문제였습니다.
처음에는 완전 탐색인가 하고 이중 for문으로만 돌았다가 실패하고 DP로 풀 수 있을 것 같기도 해서 시도해봤는데 시간 문제 상 풀어보진 못했는데 DFS나 DP가 가능하다면 다시 한번 풀어서 업로드 해보겠습니다!
각 숫자는 +, - 부호에 따른 2가지 경우의 수가 발생합니다.
각 노드들을 하나씩 탐색하면서 인접 노드들(+,-)를 queue에 넣어주고 pop해서 노드들과 누적식으로 더해줍니다.
idx가 numbers의 길이와 동일할 때, 즉 모든 수를 다 쓰고, 계산 값이 target과 동일할 때 answer을 증가시킵니다
=> [Programmers - 타겟 넘버] seulah

BOJ/jaehong/10_week/타겟넘버.js
숫자 배열에 있는 각 숫자에 대해 +나 -를 붙여 모든 가능한 결과를 만들어보고, 그 결과가 목표값과 일치하는 경우를 세었습니다. 여기서는 DFS(깊이 우선 탐색)를 사용해서, 배열의 첫 번째 숫자부터 마지막 숫자까지 하나씩 선택하면서, 현재까지의 합에 해당 숫자를 더하거나 빼는 두 가지 경우를 계속 재귀적으로 처리했습니다. 
결국 배열의 끝에 도달했을 때, 현재까지의 합이 목표값과 같으면 카운트를 하나씩 올리는 방식입니다
=> [Programmers-타겟넘버] jaehong

BOJ/yein/10_week/[Baekjoon-15683] 감시(실패).py, BOJ/yein/10_week/[programmers] 타겟넘버.py
타겟넘버 풀이와..
망한 감시 풀이를 가져왔습니다. 다시... 다시 풀어서 올릴건데 열심히 푼 게 아쉬워서...
`DFS` , 재귀 방식으로 풀었습니다.
이진트리와 같은 모양으로 분기하는데, numbers 배열의 값이 +, -로 각각 나눠집니다.
이때, 트리의 높이는 numbers 배열의 값 개수와 같게 됩니다.
카테고리에 풀이방식이 나와있어서 쉽게 접근할..... 수 있었지만!! DFS와 BFS는 array 출력 또는 손코딩으로 시험 본 것 말고는 처음 접해봐서 쪼금 헤맸습니다 ㅎㅎ DFS/BFS 활용하는 문제는 더 풀어봐야겠어요!
망했지만 아쉬워서 올려봅니다...
`그리디 알고리즘`으로 접근했고, 이 방식으로는 최적해를 찾을 수가 없었습니다...
기본적인 예제랑, 몇몇 테스트케이스는 통과할 수 있습니다. 다만, 접근 방식 자체가 잘못되어 다시 풀어야 합니다 ㅠ_ㅠ..
대표적으로, 아래와 같은 테스트케이스는 통과할 수 없습니다...
다시 풀어오겠습니다.....
```
5 5 
1 0 0 0 1 
0 1 0 1 0
0 0 0 0 0
0 1 0 1 0
1 0 0 0 1
```
=> [Programmers-타겟넘버] yein

BOJ/jihoon/10week/단축키 지정.cpp
1283 문제는 문자열 문제입니다.
단축키를 지정해주고 단축키가 존재하는지 판단하는 조건들만 잘 걸어주면 쉽게 풀 수 있는 문제입니다.
먼저 알파벳은 대소문자를 구분하지 않기 위해서 모두 소문자로 변환해서 넣었습니다.
그리고 단축키는 유일하게 넣고 빠르게 찾기 위해서 unordered_map에 단축키를 넣도록 했습니다.
이후, 조건 1,2,3에 대해서 진행하는데
조건1 - 각 단어의 첫번째 알파벳 판단 -> 단축키 map에 없다면 해당 단어 출력 및 단축키 등록
조건2 - 모든 단어를 조회하며 단축키 아닌 알파벳을 출력 및 단축키 등록
조건3 - 그냥 출력
이렇게 설계해서 풀면 완료됩니다.
=> [Baekjoon-1283] jihoon

BOJ/jeongbeen/12_week/배열_복원하기.java
배열 복원하기 문제입니다.
A 배열 범위까지만 탐색하며 X, Y 이전 범위까지는 A 배열의 값으로 넣고, 이후 탐색부터는 가지고 있는 이전 범위의 A배열의 값으로부터 값을 빼서 A 배열을 구합니다.
=> [Baekjoon-16967] jeongbeen

BOJ/seulah/12_week/근손실.py
> 이것도.. 저번주..ㅎㅎ
음..백트레킹 문제였던 것 같은데 파이썬은 `Itertools`이라는 녀석 덕분에 쉽게 모든 순열을 구하고
분기 걸어서 카운트 해주었습니다!!! 
코테에 itertools 못쓰게 하는 곳도 많아서 따로 백트레킹으로도 풀이해보겠습니다!
=> [Baekjoon-18429] seulah

BOJ/jeongbeen/12_week/수_이어_쓰기.java
난이도에 비해 상당히...... 오래걸린 문제입니다.
greedy 하게 숫자를 하나씩 증가시키며 해당 숫자가 포함된 수가 있다면 바로바로 문자열에서 제거하는 식으로 진행하였습니다.
탐색방법은 현재 숫자의 각 자리수를 문자열의 수와 매번 비교하였습니다.
=> [Baekjoon-1515] 타임어택 문제풀이

BOJ/jihoon/12week/근손실.cpp
이 문제는 백트래킹 문제입니다.
운동 키드의 조합을 쭉 돌면서 근육량이 500 미만이 되면 백트래킹하고 다른 루트를 탐색합니다.
그리고 모든 키트를 다 돌았을 때, 500 이상을 유지하고 있으면 경우의 수를 증가시킵니다.
모든 경우의 수에 대해서 탐색하고 가능했던 경우의 수를 출력하면 완료입니다.
=> [Baekjoon-18429] jihoon
